export const from: {[key: string]: string} = {
    slate: 'from-slate-500',
    gray: 'from-gray-500',
    zinc: 'from-zinc-500',
    neutral: 'from-neutral-500',
    stone: 'from-stone-500',
    red: 'from-red-500',
    orange: 'from-orange-500',
    amber: 'from-amber-500',
    yellow: 'from-yellow-500',
    lime: 'from-lime-500',
    green: 'from-green-500',
    cyan: 'from-cyan-500',
    blue: 'from-blue-500',
    indigo: 'from-indigo-500',
    purple: 'from-purple-500',
    pink: 'from-pink-500',
    violet: 'from-violet-500',
    rose: 'from-rose-500',
    teal: 'from-teal-500'
};

export const to: { [key: string]: string } = {
    slate: 'to-slate-300',
    gray: 'to-gray-300',
    zinc: 'to-zinc-300',
    neutral: 'to-neutral-300',
    stone: 'to-stone-300',
    red: 'to-red-300',
    orange: 'to-orange-300',
    amber: 'to-amber-300',
    yellow: 'to-yellow-300',
    lime: 'to-lime-300',
    green: 'to-green-300',
    cyan: 'to-cyan-300',
    blue: 'to-blue-300',
    indigo: 'to-indigo-300',
    purple: 'to-purple-300',
    pink: 'to-pink-300',
    violet: 'to-violet-300',
    rose: 'to-rose-300',
    teal: 'to-teal-300'
};
